// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkicnjyinowauwtgpvcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraWNuanlpbm93YXV3dGdwdmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzk4NDcsImV4cCI6MjA2MzY1NTg0N30.-lEwqIqCy4In6OB-DIRcFI4cPi32ro2SQ44wzYy9gFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);